name=input("Enter name: ")
print(f"Hello, Welcome {name}")
num1=int(input("Enter the first number: "))
num2=int(input("Enter the second number: "))
print(f"the sum of {num1} and {num2} is {num1+ num2}")
print(f"the difference of {num1} and {num2} is {num1-num2}")
print(f"the product of {num1} and {num2} is {num1*num2}")
print(f"the quotient of {num1} and {num2} is {num1/num2}")
print(f"the remainder of {num1} and {num2} is {num1%num2}")
